// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureBootDashboard.Api.Data;

#nullable disable

namespace SecureBootDashboard.Api.Data.Migrations
{
    [DbContext(typeof(SecureBootDbContext))]
    [Migration("20251204151938_AddClientSinkConfiguration")]
    partial class AddClientSinkConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecureBootDashboard.Api.Data.ApplicationSettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("RequiresRestart")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApplicationSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "QueueProcessor",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Enable or disable the queue processor background service",
                            IsSensitive = false,
                            Key = "QueueProcessor:Enabled",
                            RequiresRestart = true,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "true",
                            ValueType = "bool"
                        },
                        new
                        {
                            Id = 2,
                            Category = "QueueProcessor",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Maximum number of messages to process in each batch",
                            IsSensitive = false,
                            Key = "QueueProcessor:MaxMessages",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "10",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 3,
                            Category = "QueueProcessor",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Interval between queue processing cycles when messages are present",
                            IsSensitive = false,
                            Key = "QueueProcessor:ProcessingInterval",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "00:00:02",
                            ValueType = "timespan"
                        },
                        new
                        {
                            Id = 4,
                            Category = "QueueProcessor",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Interval to check queue when it was previously empty",
                            IsSensitive = false,
                            Key = "QueueProcessor:EmptyQueuePollInterval",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "00:00:10",
                            ValueType = "timespan"
                        },
                        new
                        {
                            Id = 5,
                            Category = "ClientUpdate",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Latest available client version",
                            IsSensitive = false,
                            Key = "ClientUpdate:LatestVersion",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "\"1.5.0.0\"",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 6,
                            Category = "ClientUpdate",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Minimum supported client version",
                            IsSensitive = false,
                            Key = "ClientUpdate:MinimumVersion",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "\"1.3.0.0\"",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 7,
                            Category = "ClientUpdate",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Whether client update is mandatory",
                            IsSensitive = false,
                            Key = "ClientUpdate:IsUpdateRequired",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "false",
                            ValueType = "bool"
                        },
                        new
                        {
                            Id = 8,
                            Category = "ClientUpdate",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "URL to download the latest client package",
                            IsSensitive = false,
                            Key = "ClientUpdate:DownloadUrl",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "\"https://secbootcert.queue.core.windows.net/client-packages/SecureBootWatcher-Client-latest.zip\"",
                            ValueType = "string"
                        },
                        new
                        {
                            Id = 9,
                            Category = "SecureBootReadiness",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Days before expiration to show warning (3 years)",
                            IsSensitive = false,
                            Key = "SecureBootReadiness:CertificateExpirationWarningDays",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "1095",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 10,
                            Category = "SecureBootReadiness",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Days before expiration to show critical alert (1 year)",
                            IsSensitive = false,
                            Key = "SecureBootReadiness:CertificateExpirationCriticalDays",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "365",
                            ValueType = "int"
                        },
                        new
                        {
                            Id = 11,
                            Category = "SecureBootReadiness",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Require Windows UEFI CA 2023 certificate for readiness",
                            IsSensitive = false,
                            Key = "SecureBootReadiness:RequireWindowsUEFICA2023",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "true",
                            ValueType = "bool"
                        },
                        new
                        {
                            Id = 12,
                            Category = "SecureBootReadiness",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Require OEM certificates to be valid (not expired)",
                            IsSensitive = false,
                            Key = "SecureBootReadiness:RequireOemCertificatesValid",
                            RequiresRestart = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = "true",
                            ValueType = "bool"
                        });
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.ClientSinkConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureQueueAuthMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AzureQueueCertPassword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AzureQueueCertPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AzureQueueCertStoreLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AzureQueueCertStoreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AzureQueueCertThumbprint")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AzureQueueClientId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AzureQueueClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AzureQueueConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AzureQueueMaxSendRetryCount")
                        .HasColumnType("int");

                    b.Property<string>("AzureQueueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AzureQueueServiceUri")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AzureQueueTenantId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AzureQueueVisibilityTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EnableAzureQueue")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableFileShare")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableWebApi")
                        .HasColumnType("bit");

                    b.Property<string>("ExecutionStrategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("FileShareAppendTimestamp")
                        .HasColumnType("bit");

                    b.Property<string>("FileShareExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileShareRootPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("int");

                    b.Property<int>("RetryDelaySeconds")
                        .HasColumnType("int");

                    b.Property<string>("SinkPriority")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("UseExponentialBackoff")
                        .HasColumnType("bit");

                    b.Property<string>("WebApiBaseAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WebApiCertPassword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WebApiCertPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("WebApiCertStoreLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebApiCertStoreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebApiCertThumbprint")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WebApiIngestionRoute")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("WebApiTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("WebApiUseCertAuth")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ClientSinkConfig", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AzureQueueAuthMethod = "DefaultAzureCredential",
                            AzureQueueCertStoreLocation = "CurrentUser",
                            AzureQueueCertStoreName = "My",
                            AzureQueueMaxSendRetryCount = 5,
                            AzureQueueName = "secureboot-reports",
                            AzureQueueVisibilityTimeoutSeconds = 300,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            Description = "Default client sink configuration. Configure via Admin Settings.",
                            EnableAzureQueue = false,
                            EnableFileShare = false,
                            EnableWebApi = true,
                            ExecutionStrategy = "StopOnFirstSuccess",
                            FileShareAppendTimestamp = true,
                            FileShareExtension = ".json",
                            IsActive = true,
                            MaxRetryAttempts = 3,
                            RetryDelaySeconds = 300,
                            SinkPriority = "WebApi,AzureQueue,FileShare",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "System",
                            UseExponentialBackoff = false,
                            WebApiCertStoreLocation = "LocalMachine",
                            WebApiCertStoreName = "My",
                            WebApiIngestionRoute = "/api/SecureBootReports",
                            WebApiTimeoutSeconds = 30,
                            WebApiUseCertAuth = false
                        });
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.DeviceCleanupConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CleanupSchedule")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("DeleteAssociatedData")
                        .HasColumnType("bit");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("InactiveDaysThreshold")
                        .HasColumnType("int");

                    b.Property<int>("LastCleanupDeviceCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastCleanupRunUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NotificationEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("NotifyOnCleanup")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("DeviceCleanupConfig", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CleanupSchedule = "0 2 * * *",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DeleteAssociatedData = true,
                            Enabled = false,
                            InactiveDaysThreshold = 90,
                            LastCleanupDeviceCount = 0,
                            NotifyOnCleanup = false,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChassisTypesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DomainName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("FirmwareReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FleetId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("IsVirtualMachine")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OSBuildNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OSProductType")
                        .HasColumnType("int");

                    b.Property<string>("OSVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("UEFISecureBootEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserPrincipalName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VirtualizationPlatform")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineName");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.MutualTlsConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowSelfSignedCertificates")
                        .HasColumnType("bit");

                    b.Property<string>("AllowedThumbprints")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("CheckCertificateRevocation")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EnableDetailedLogging")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableIssuerAllowlist")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableThumbprintAllowlist")
                        .HasColumnType("bit");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("ExpirationGracePeriodDays")
                        .HasColumnType("int");

                    b.Property<bool>("RequireClientAuthEku")
                        .HasColumnType("bit");

                    b.Property<int>("RevocationCheckTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("ValidateCertificateChain")
                        .HasColumnType("bit");

                    b.Property<bool>("ValidateCertificateValidity")
                        .HasColumnType("bit");

                    b.Property<string>("ValidationNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("MutualTlsConfig", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowSelfSignedCertificates = false,
                            CheckCertificateRevocation = true,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = "System",
                            EnableDetailedLogging = false,
                            EnableIssuerAllowlist = true,
                            EnableThumbprintAllowlist = false,
                            Enabled = false,
                            ExpirationGracePeriodDays = 0,
                            RequireClientAuthEku = true,
                            RevocationCheckTimeoutSeconds = 10,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 1, 14, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedBy = "System",
                            ValidateCertificateChain = true,
                            ValidateCertificateValidity = true,
                            ValidationNotes = "Default mutual TLS configuration. Update via Admin Settings."
                        });
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.PendingCommandEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FetchCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastFetchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ScheduledForUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Status");

                    b.HasIndex("DeviceId", "Status");

                    b.ToTable("PendingCommands", (string)null);
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.SecureBootEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RawXml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("SecureBootEvents", (string)null);
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.SecureBootReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlertsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificatesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientVersion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeploymentState")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistryStateJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("DeviceId");

                    b.ToTable("SecureBootReports", (string)null);
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.TrustedCertificateAuthorityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateDataBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRootCa")
                        .HasColumnType("bit");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("NotAfter")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Thumbprint256")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CommonName");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("IsRootCa");

                    b.HasIndex("NotAfter");

                    b.HasIndex("Thumbprint")
                        .IsUnique();

                    b.ToTable("TrustedCertificateAuthorities", (string)null);
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.WindowsBuildEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSecure")
                        .HasColumnType("bit");

                    b.Property<string>("KbArticle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MajorBuild")
                        .HasColumnType("int");

                    b.Property<int?>("MinorBuild")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WindowsVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildNumber");

                    b.HasIndex("IsLatest");

                    b.HasIndex("WindowsVersionId", "BuildNumber")
                        .IsUnique();

                    b.ToTable("WindowsBuilds", (string)null);
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.WindowsVersionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique();

                    b.ToTable("WindowsVersions", (string)null);
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.PendingCommandEntity", b =>
                {
                    b.HasOne("SecureBootDashboard.Api.Data.DeviceEntity", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.SecureBootEventEntity", b =>
                {
                    b.HasOne("SecureBootDashboard.Api.Data.SecureBootReportEntity", "Report")
                        .WithMany("Events")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.SecureBootReportEntity", b =>
                {
                    b.HasOne("SecureBootDashboard.Api.Data.DeviceEntity", "Device")
                        .WithMany("Reports")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.WindowsBuildEntity", b =>
                {
                    b.HasOne("SecureBootDashboard.Api.Data.WindowsVersionEntity", "Version")
                        .WithMany("Builds")
                        .HasForeignKey("WindowsVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.DeviceEntity", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.SecureBootReportEntity", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("SecureBootDashboard.Api.Data.WindowsVersionEntity", b =>
                {
                    b.Navigation("Builds");
                });
#pragma warning restore 612, 618
        }
    }
}
